CREATE TABLE IF NOT EXISTS post (
  title varchar(240) DEFAULT NULL,
  slag varchar(240) NOT NULL DEFAULT '',
  date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  link varchar(512) DEFAULT NULL,
  content text,
  PRIMARY KEY (slag),
  KEY slag (slag)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS rss (
  url varchar(300) DEFAULT NULL,
  UNIQUE (url)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;